### PR TITLE
CL-36689 | Update PEAR checksums for patched files.

### PR DESCRIPTION
**Pull request by Skarlso**
Sorry, this was previously merged into the wrong base. :/

### CODE REVIEW

**Comment by bronislav** [comment]
@Skarlso May you squash commits, please?

**Review by bronislav — APPROVED** [review]

**Comment by Skarlso** [comment]
Ofc.

**Review by kozmate — APPROVED** [review]

**Review by jamesiarmes — CHANGES_REQUESTED** [review]
This was already merged into the correct branch and a tag cut by @glennpratt.

**Comment by Skarlso** [comment]
@jamesiarmes that was `v1.3.2-acquia`. I need `v1.3.2-acquia.2`.
The base branch for that previous PR was incorrectly set.

**Comment by Skarlso** [comment]
OH!! Glenn set the new base branch. :O But... Why would he do that?

**Pull request closed without merging**
