### PR TITLE
CL-36689 | Update PEAR checksums for patched files.

### PR DESCRIPTION
**Pull request by Skarlso**
… they conflict.

### CODE REVIEW

**Comment by bronislav** [comment]
@Skarlso Maybe instead of deleting checksum it will be better to update them to be correct?

**Comment by Skarlso** [comment]
@bronislav I was debating that... But it's every single file. :D Also, I didn't see the point since this is an acquian private fork.

but if you insight, I'll write a script :D

**Comment by Skarlso** [comment]
you know what, I'll do it... let me get my `sed` && `awk` skills up :)

**Comment by pdrakeweb** [comment]
@Skarlso in what way do they interfere with deployment?  Is there a particular deployment method that is failing with these checksums?  Are all of the checksums wrong or just the one for the file we modified?

**Comment by Skarlso** [comment]
The checksums are wrong and they are failing when we are trying to install them via php. I'll fix the checksums to be correct. It's a "problem" because on each release or when you change a file you don't update package.xml file to contain the correct checksum.

**Comment by bronislav** [comment]
@Skarlso So, it should be in the requirements then, that this checksum should be updated upon change.

**Comment by Skarlso** [comment]
yep

**Comment by Skarlso** [comment]
The scripts used:

```ruby
require 'nokogiri'

lines = []
File.open('output.txt', 'r').each { |l| lines << l }
doc = Nokogiri::XML(File.open("package.xml"))
lines.each do |l|
    cols = l.split(' ')
    doc.css("contents/dir/file[@name='#{cols[1]}']").attr('md5sum').value = cols[0]
end
doc.write_to(File.open('package.xml', 'w'))
```

To get all the new sums:

```
find Net/. -type f -name "*.php" -exec md5sum {} \; | sort -k 2 >> output.txt
```

**Review by bronislav — APPROVED** [review]
LGTM

**Review by blkperl — APPROVED** [review]

**Review by malikbakt — APPROVED** [review]

**Review by pdrakeweb — APPROVED** [review]
I filed CL-36894 to write an automated test that would catch this.

**Comment by glennpratt** [comment]
Should we be bumping the release version to '1.3.2.1' since this this actually differs from 1.3.2?

EDIT: meh

**Comment by Skarlso** [comment]
This was merged into the wrong branch. :( :(

**Comment by Skarlso** [comment]
Dang it. Was supposed to be merged into acquia.2

**Pull request merged**
